# Generated by Django 5.2.3 on 2025-07-07 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Asta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.CharField(max_length=250)),
                ('data_inizio', models.DateTimeField(verbose_name='data inizio')),
                ('data_fine', models.DateField()),
                ('reserve_price', models.FloatField()),
                ('buynow_price', models.FloatField()),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(default='auction_images/default.jpg', upload_to='auction_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aste', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=models.SET(999), to='aste.categoria')),
            ],
            options={
                'verbose_name_plural': 'Aste',
            },
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('asta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to='aste.asta')),
                ('offerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Offerte',
                'ordering': ['-data'],
            },
        ),
    ]
