# Generated by Django 5.2.3 on 2025-07-07 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asta',
            name='image',
        ),
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='galleria/')),
                ('asta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='aste.asta')),
            ],
        ),
    ]
