# Generated by Django 5.2.3 on 2025-07-09 17:22

import aste.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aste', '0003_alter_allegato_immagine_alter_asta_descrizione'),
    ]

    operations = [
        migrations.AddField("asta", "is_active", models.BooleanField(default=False)),
    ]
