# Generated by Django 5.2.3 on 2025-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aste', '0004_add_alter_add_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='importo',
            field=models.FloatField(default=0),
        ),
    ]
