# Generated by Django 5.2.3 on 2025-07-11 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aste', '0005_offerta_importo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AstaSeguita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='aste.asta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aste_seguite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asta')},
            },
        ),
    ]
